version: '3.1'
services:
    db:
        image: postgres:16.1
        environment:
            POSTGRES_DB: univer_postgre
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            PGDATA: /var/lib/postgresql/data/pgdata
        ports:
            - 5432:5432
        volumes:
            - type: bind
              source: ./bd_data
              target: /var/lib/postgresql/data